
import Crmsconnect.CP;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.coobird.thumbnailator.Thumbnails;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafiz 01
 */
public class AddCrminal extends javax.swing.JFrame {

    /**
     * Creates new form AddCrminal
     */
    Connection conn=null;

        PreparedStatement pst;
    public AddCrminal() {
        initComponents();
        conn=(Connection) CP.dbconnect();
        setTitle("Add Criminal");
        updatecr.setVisible(false);
          
            
        
    }

    AddCrminal(String Updatecriminal) {
        
        setTitle("Police Details");
         conn=(Connection) CP.dbconnect();
          initComponents();

        try {
            
       
        PreparedStatement pst=conn.prepareStatement("Select * from criminalinfo Where crminal_id=?");
                    pst.setString(1, Updatecriminal);
                    ResultSet res=pst.executeQuery();
                    if(res.next()){
                    fname.setText(res.getString("fname"));
                    lname.setText(res.getString("lname"));
                     address.setText(res.getString("address"));
                   agecr.setText(res.getString("age"));
                    dateifbirth.setText(res.getString("dateofbirth"));
                    fir_id.setText(res.getString("fir_id"));
                   cr_id.setText(res.getString("crminal_id"));
                  
                    }
                    
            
          
         } catch (Exception e) {
             System.out.println(e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pstation = new javax.swing.JComboBox<>();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        agecr = new javax.swing.JTextField();
        fir_id = new javax.swing.JTextField();
        addcriminalbtn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        cr_id = new javax.swing.JTextField();
        dateifbirth = new javax.swing.JTextField();
        clrcrminal = new javax.swing.JToggleButton();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        imagelabel = new javax.swing.JLabel();
        uploadebtn = new javax.swing.JButton();
        updatecr = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(176, 176, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD CRIMINAL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 60));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<-");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("First Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 30, -1, 30));

        jLabel4.setText("Last Name:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 78, 72, 30));

        jLabel5.setText("Age:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 126, 60, 30));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 166, -1, -1));

        jLabel6.setText("Gender:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 162, 60, 30));

        jLabel7.setText("Date of birth:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 204, -1, 30));

        jLabel8.setText("Address:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 260, 60, 30));

        jLabel9.setText("F.I.R ID:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 391, 60, 30));

        jLabel10.setText("Police Station:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 391, 81, 30));

        pstation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andheri", "Malad", "Borivali", "Jogeshwari" }));
        jPanel3.add(pstation, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 395, -1, -1));
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 34, 224, -1));
        jPanel3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 82, 224, -1));
        jPanel3.add(agecr, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 130, 78, -1));
        jPanel3.add(fir_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 395, 101, -1));

        addcriminalbtn.setBackground(new java.awt.Color(242, 242, 242));
        addcriminalbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addcriminalbtn.setText("Submit");
        addcriminalbtn.setBorder(null);
        addcriminalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcriminalbtnActionPerformed(evt);
            }
        });
        jPanel3.add(addcriminalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 449, 111, 44));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 268, -1, -1));

        jLabel11.setText("Criminal ID:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 133, -1, -1));
        jPanel3.add(cr_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 130, 72, -1));
        jPanel3.add(dateifbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 208, 227, -1));

        clrcrminal.setBackground(new java.awt.Color(242, 242, 242));
        clrcrminal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clrcrminal.setText("Clear");
        clrcrminal.setBorder(null);
        clrcrminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrcrminalActionPerformed(evt);
            }
        });
        jPanel3.add(clrcrminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 449, 111, 44));

        jDesktopPane5.setBackground(new java.awt.Color(204, 204, 204));

        imagelabel.setBackground(new java.awt.Color(255, 255, 255));
        imagelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jDesktopPane5.setLayer(imagelabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jDesktopPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 30, -1, -1));

        uploadebtn.setBackground(new java.awt.Color(242, 242, 242));
        uploadebtn.setText("Uploade image");
        uploadebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadebtnActionPerformed(evt);
            }
        });
        jPanel3.add(uploadebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 120, 40));

        updatecr.setBackground(new java.awt.Color(242, 242, 242));
        updatecr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatecr.setText("Update");
        updatecr.setBorder(null);
        updatecr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecrActionPerformed(evt);
            }
        });
        jPanel3.add(updatecr, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 449, 111, 44));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 540));
        jPanel3.getAccessibleContext().setAccessibleName("");
        jPanel3.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addcriminalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcriminalbtnActionPerformed
        
        System.out.println("Hellow");
        String fnamecr=fname.getText();
        String lnamecr=lname.getText();
        String age=agecr.getText();
        String criminalid=cr_id.getText();
        String gendercr=gender.getSelectedItem().toString();
        String addresscr=address.getText();
        String pstationcr=pstation.getSelectedItem().toString();
        String dobirth=dateifbirth.getText();
        String firforen=fir_id.getText();
        if(fnamecr.isEmpty()||lnamecr.isEmpty()||age.isEmpty()||criminalid.isEmpty()||addresscr.isEmpty()||pstationcr.isEmpty() ||  criminalimg==null){
            JOptionPane.showMessageDialog(this,"Please Fill all the Deatails","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        PreparedStatement pst;
        try {
            pst = conn.prepareStatement("insert into criminalinfo (crminal_id,fname ,lname ,age ,gender ,dateofbirth ,address,policestation,fir_id,pic)values (?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,criminalid);
            pst.setString(2,fnamecr);
            pst.setString(3,lnamecr);
            pst.setString(4,age);
            pst.setString(5,gendercr);
            pst.setString(6,dobirth);
            pst.setString(7, addresscr);
            pst.setString(8, pstationcr);
            pst.setString(9,firforen);
            pst.setBytes(10, criminalimg );
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Added Successfully");
            fname.setText("");
            lname.setText("");
            cr_id.setText("");
            address.setText("");
            agecr.setText("");
            dateifbirth.setText("");
            fir_id.setText("");
            
            
        } catch (SQLException ex) {
            
            Logger.getLogger(AddCrminal.class.getName()).log(Level.SEVERE, null, ex);
        } 
            
            
        
    }//GEN-LAST:event_addcriminalbtnActionPerformed

    private void clrcrminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrcrminalActionPerformed
            fname.setText("");
            lname.setText("");
            cr_id.setText("");
            address.setText("");
            agecr.setText("");
            fir_id.setText("");
            dateifbirth.setText("");
    }//GEN-LAST:event_clrcrminalActionPerformed

    private void uploadebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadebtnActionPerformed
       JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f= chooser.getSelectedFile();
       filename=f.getAbsolutePath();
        try {
            File image=new File(filename);
            BufferedImage thumbnail =(BufferedImage) Thumbnails.of(image).size(154,150).asBufferedImage();
            ByteArrayOutputStream os=new ByteArrayOutputStream();
            ImageIO.write(thumbnail,"jpeg",os);
            InputStream is=new ByteArrayInputStream(os.toByteArray());
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum;(readnum=is.read(buf))!=-1;)
            {
            
            bos.write(buf,0,readnum);
            }
            
            viewimage =new ImageIcon(thumbnail);
            imagelabel.setIcon(viewimage);
            
             criminalimg=bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
       
    }//GEN-LAST:event_uploadebtnActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        try {
            Criminalpage cr=new Criminalpage();
            cr.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AddCrminal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void updatecrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecrActionPerformed
       
                try {                                         
                    
                    String fnamecr=fname.getText();
                    String lnamecr=lname.getText();
                    String age=agecr.getText();
                    String criminalid=cr_id.getText();
                    String gendercr=gender.getSelectedItem().toString();
                    String addresscr=address.getText();
                    String pstationcr=pstation.getSelectedItem().toString();
                    String dobirth=dateifbirth.getText();
                    String firforen=fir_id.getText();
                    
                    if(fnamecr.isEmpty()||lnamecr.isEmpty()||age.isEmpty()||criminalid.isEmpty()||addresscr.isEmpty()||pstationcr.isEmpty()){
                        JOptionPane.showMessageDialog(this,"Please Fill all the Deatails","ERROR",JOptionPane.ERROR_MESSAGE);
                    }
                    PreparedStatement pst;
                    
                    pst = conn.prepareStatement("update criminalinfo set fname=? ,lname=? ,age=? ,gender=? ,dateofbirth=? ,address=?,policestation=?,fir_id=? where crminal_id=?");
                    pst.setString(1,fnamecr);
                    pst.setString(2,lnamecr);
                    pst.setString(3,age);
                    pst.setString(4,gendercr);
                    pst.setString(5,dobirth);
                    pst.setString(6, addresscr);
                    pst.setString(7, pstationcr);
                    pst.setString(8,firforen);
                    pst.setString(9,criminalid);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Updated Successfully");
                } catch (SQLException ex) {
                    Logger.getLogger(AddCrminal.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }//GEN-LAST:event_updatecrActionPerformed
        
            
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCrminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCrminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCrminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCrminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCrminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addcriminalbtn;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField agecr;
    private javax.swing.JToggleButton clrcrminal;
    private javax.swing.JTextField cr_id;
    private javax.swing.JTextField dateifbirth;
    private javax.swing.JTextField fir_id;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JComboBox<String> pstation;
    private javax.swing.JToggleButton updatecr;
    private javax.swing.JButton uploadebtn;
    // End of variables declaration//GEN-END:variables

String filename= null;
private ImageIcon viewimage=null;
byte [] criminalimg=null;
}
