
import Crmsconnect.CP;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Student
 */
public class AddFIR extends javax.swing.JFrame {

    /**
     * Creates new form AddFIR
     */
    
     Connection conn=null;
     PreparedStatement pst;
    public AddFIR() {
        initComponents();
        conn=(Connection) CP.dbconnect();
        setTitle("FIR Details");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        namefir = new javax.swing.JTextField();
        firidfield = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        typefir = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        sectionfir = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        addressfir = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        detailsfir = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        firjComboBox = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        genderfit = new javax.swing.JComboBox<>();
        datefir = new javax.swing.JTextField();
        firjButton = new javax.swing.JButton();
        firclrjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(176, 176, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(176, 176, 176));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD FIR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 510, 80));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "FIR INFO", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("DATE OF CRIME :");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 58, -1, -1));

        jLabel30.setText("NAME :");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 21, -1, -1));

        jLabel31.setText("FIR ID :");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 123, -1, -1));
        jPanel6.add(namefir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 18, 326, -1));

        firidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel6.add(firidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 120, 111, -1));

        jLabel32.setText("TYPE OF CRIME :");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 172, -1, -1));
        jPanel6.add(typefir, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 169, 326, -1));

        jLabel33.setText("DETAILS :");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 209, -1, -1));

        jLabel34.setText("SECTION :");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 123, -1, -1));
        jPanel6.add(sectionfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 120, -1));

        jLabel35.setText("ADDRESS:");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 313, -1, -1));

        addressfir.setColumns(20);
        addressfir.setRows(5);
        jScrollPane8.setViewportView(addressfir);

        jPanel6.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 313, 326, -1));

        detailsfir.setColumns(20);
        detailsfir.setRows(5);
        jScrollPane9.setViewportView(detailsfir);

        jPanel6.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 209, 330, -1));

        jLabel36.setText("Police Station:");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 53, -1, -1));

        firjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Borivli", "Malad", "Jogeshwari", "Andheri" }));
        jPanel6.add(firjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 50, 101, -1));

        jLabel37.setText("Gender:");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 86, -1, -1));

        genderfit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel6.add(genderfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 84, 101, -1));
        jPanel6.add(datefir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, -1));

        firjButton.setText("Submit");
        firjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(firjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 434, 116, 38));

        firclrjButton.setText("Clear");
        firclrjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firclrjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(firclrjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 434, 116, 38));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 650, 500));
        jPanel6.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void firjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firjButtonActionPerformed
        String firid=firidfield.getText();
        String fname=namefir.getText();
        String docrime=datefir.getText();
        String policestation=firjComboBox.getSelectedItem().toString();
        String gender=genderfit.getSelectedItem().toString();
        String section=sectionfir.getText();
        String typc=typefir.getText();
        String details=detailsfir.getText();
        String address=addressfir.getText();
        
        if (firid.isEmpty()|| fname.isEmpty() || docrime.isEmpty() || section.isEmpty() || typc.isEmpty() || details.isEmpty() || address.isEmpty() ){
        JOptionPane.showMessageDialog(this,"Please Fill all the Deatails","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
        
            try {
                pst = conn.prepareStatement("insert into firinfo (fir_id,fname, dateofcrime,policestation, gender,section,typeofcrime,otherdetails,address)values (?,?,?,?,?,?,?,?,?)");
                pst.setString(1, firid);
                pst.setString(2, fname);
                pst.setString(3, docrime);
                pst.setString(4, policestation);
                pst.setString(5, gender);
                pst.setString(6, section);
                pst.setString(7, typc);
                pst.setString(8, details);
                pst.setString(9, address);
                pst.executeUpdate();
                 JOptionPane.showMessageDialog(null,"Added Successfully");
                 firidfield.setText("");
                namefir.setText("");
                datefir.setText("");
                sectionfir.setText("");
                typefir.setText("");
                detailsfir.setText("");
                addressfir.setText("");
                 
                
            } catch (SQLException ex) {
                Logger.getLogger(AddFIR.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_firjButtonActionPerformed

    private void firclrjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firclrjButtonActionPerformed
                firidfield.setText("");
                namefir.setText("");
                datefir.setText("");
                sectionfir.setText("");
                typefir.setText("");
                detailsfir.setText("");
                addressfir.setText("");
    }//GEN-LAST:event_firclrjButtonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       
         try {
             FIR firp=new FIR();
             firp.setVisible(true);
             dispose();
         } catch (SQLException ex) {
             Logger.getLogger(AddFIR.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFIR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressfir;
    private javax.swing.JTextField datefir;
    private javax.swing.JTextArea detailsfir;
    private javax.swing.JButton firclrjButton;
    private javax.swing.JTextField firidfield;
    private javax.swing.JButton firjButton;
    private javax.swing.JComboBox<String> firjComboBox;
    private javax.swing.JComboBox<String> genderfit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField namefir;
    private javax.swing.JTextField sectionfir;
    private javax.swing.JTextField typefir;
    // End of variables declaration//GEN-END:variables
}
