
import Crmsconnect.CP;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.String.format;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.coobird.thumbnailator.Thumbnails;









/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafiz 01
 */
public class Addpolice extends javax.swing.JFrame {

    /**
     * Creates new form Addpolice
     */
    
    Connection conn=null;

        PreparedStatement pst;
    public Addpolice() {
        initComponents();
            conn=(Connection) CP.dbconnect();
            setTitle("Police Details");
            updatepolice.setVisible(false);
 
    }

    Addpolice(String Updatepolice) throws SQLException {
        initComponents();
        setTitle("Police Details");
         conn=(Connection) CP.dbconnect();

        try {
            
       
        PreparedStatement pst=conn.prepareStatement("Select * from policeinfo Where police_id=?");
                    pst.setString(1, Updatepolice);
                    ResultSet res=pst.executeQuery();
                    if(res.next()){
                    Fnamepolice.setText(res.getString("fname"));
                    lnamepolice.setText(res.getString("lname"));
                    deppolice.setText(res.getString("department"));
                    emailpolice.setText(res.getString("email"));
                    policeadhar.setText(res.getString("adhaar"));
                    policedesig.setText(res.getString("designation"));
                    policeidjTextField.setText(res.getString("police_id"));
                    }
                    
            
          
         } catch (Exception e) {
             System.out.println(e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailpolice = new javax.swing.JTextField();
        Fnamepolice = new javax.swing.JTextField();
        lnamepolice = new javax.swing.JTextField();
        deppolice = new javax.swing.JTextField();
        addpolicesub = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        policeadhar = new javax.swing.JTextField();
        policedesig = new javax.swing.JTextField();
        clearpolicebtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        policeidjTextField = new javax.swing.JTextField();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        imagelabel = new javax.swing.JLabel();
        uploadepolicebtn = new javax.swing.JButton();
        updatepolice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 176, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD POLICE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<-");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("FIRSTNAME:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 26, -1, -1));

        jLabel3.setText("LASTNAME:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setText("DEPARTMENT:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 103, -1, -1));

        jLabel5.setText("EMAIL:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 143, -1, -1));
        jPanel2.add(emailpolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, -1));

        Fnamepolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnamepoliceActionPerformed(evt);
            }
        });
        jPanel2.add(Fnamepolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, -1));
        jPanel2.add(lnamepolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, -1));
        jPanel2.add(deppolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, -1));

        addpolicesub.setText("Submit");
        addpolicesub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpolicesubActionPerformed(evt);
            }
        });
        jPanel2.add(addpolicesub, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 301, 104, 40));

        jLabel6.setText("Adhaar no:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 183, -1, -1));

        jLabel7.setText("Designation:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 223, -1, -1));

        policeadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeadharActionPerformed(evt);
            }
        });
        jPanel2.add(policeadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 190, -1));
        jPanel2.add(policedesig, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 220, 190, -1));

        clearpolicebtn.setText("Clear");
        clearpolicebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearpolicebtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearpolicebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 301, 104, 40));

        jLabel8.setText("Police ID:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 52, 25));
        jPanel2.add(policeidjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 190, -1));

        jDesktopPane5.setBackground(new java.awt.Color(204, 204, 204));

        imagelabel.setBackground(new java.awt.Color(255, 255, 255));
        imagelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jDesktopPane5.setLayer(imagelabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jDesktopPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        uploadepolicebtn.setText("Uploade image");
        uploadepolicebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadepolicebtnActionPerformed(evt);
            }
        });
        jPanel2.add(uploadepolicebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 120, 40));

        updatepolice.setText("Update");
        updatepolice.setToolTipText("");
        updatepolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepoliceActionPerformed(evt);
            }
        });
        jPanel2.add(updatepolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 301, 104, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FnamepoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnamepoliceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnamepoliceActionPerformed

    private void addpolicesubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpolicesubActionPerformed
        PolicePage pp=new PolicePage();
        String policeid=policeidjTextField.getText();
        String fnamep=Fnamepolice.getText();
        String lnamep=lnamepolice.getText();
        String depnamep=deppolice.getText();
        String emailp=emailpolice.getText();
        String padhar=policeadhar.getText();
        String Pdesig=policedesig.getText();
        if (fnamep.isEmpty()|| lnamep.isEmpty() || depnamep.isEmpty() || emailp.isEmpty() || padhar.isEmpty() || Pdesig.isEmpty() || policeimg==null){
            JOptionPane.showMessageDialog(this,"Please Fill all the Deatails","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else{
            PreparedStatement pst;
            try {
                pst = conn.prepareStatement("insert into policeinfo (police_id,fname, lname, department, email,adhaar,designation,pic)values (?,?,?,?,?,?,?,?)");
                pst.setString(1, policeid);
                pst.setString(2,fnamep);
                pst.setString(3,lnamep);
                pst.setString(4,depnamep);
                pst.setString(5,emailp);
                pst.setString(6, padhar);
                pst.setString(7, Pdesig);
                pst.setBytes(8, policeimg);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Added Successfully");
                Fnamepolice.setText("");
                lnamepolice.setText("");
                deppolice.setText("");
                emailpolice.setText("");
                policeadhar.setText("");
                policedesig.setText("");
                policeidjTextField.setText("");
                
                
                
                
            } catch (SQLException ex) {
                
                Logger.getLogger(Addpolice.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                pp.table_update();
                pp.setVisible(true);
            } catch (SQLException ex) {
                
                Logger.getLogger(Addpolice.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
            
            
        }//if else end here
    }//GEN-LAST:event_addpolicesubActionPerformed

    private void policeadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policeadharActionPerformed

    private void clearpolicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearpolicebtnActionPerformed
       Fnamepolice.setText("");
       lnamepolice.setText("");
       deppolice.setText("");
       emailpolice.setText("");
       policeadhar.setText("");
       policedesig.setText("");
       policeidjTextField.setText("");
    }//GEN-LAST:event_clearpolicebtnActionPerformed

    private void uploadepolicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadepolicebtnActionPerformed
        JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f= chooser.getSelectedFile();
       filename=f.getAbsolutePath();
        try {
            File image=new File(filename);
            BufferedImage thumbnail =(BufferedImage) Thumbnails.of(image).size(143,134).asBufferedImage();
            ByteArrayOutputStream os=new ByteArrayOutputStream();
            ImageIO.write(thumbnail,"jpeg",os);
            InputStream is=new ByteArrayInputStream(os.toByteArray());
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum;(readnum=is.read(buf))!=-1;)
            {
            
            bos.write(buf,0,readnum);
            }
            
            viewimage =new ImageIcon(thumbnail);
            imagelabel.setIcon(viewimage);
            policeimg=bos.toByteArray();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_uploadepolicebtnActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        PolicePage pp=new PolicePage();
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void updatepoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepoliceActionPerformed
        
             
             String fnamep2=Fnamepolice.getText();
             String lnamep2=lnamepolice.getText();
             String depnamep2=deppolice.getText();
             String emailp2=emailpolice.getText();
             String padhar2=policeadhar.getText();
             String Pdesig2=policedesig.getText();
             String policeid2=policeidjTextField.getText();
             updatepolice.setVisible(true);
             
              if (fnamep2.isEmpty()|| lnamep2.isEmpty() || depnamep2.isEmpty() || emailp2.isEmpty() || padhar2.isEmpty() || Pdesig2.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please Fill all the Deatails","ERROR",JOptionPane.ERROR_MESSAGE);
            }
              try {
                    pst = conn.prepareStatement("update  policeinfo set fname=?, lname=?, department=?, email=?,adhaar=?,designation=? where police_id=?");
                     
                    pst.setString(1,fnamep2);
                    pst.setString(2,lnamep2);
                    pst.setString(3,depnamep2);
                    pst.setString(4,emailp2);
                    pst.setString(5, padhar2);
                    pst.setString(6, Pdesig2);
                    pst.setString(7, policeid2);
                  
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Updated Successfully");
                    
                 
                } catch (SQLException ex) {
                    Logger.getLogger(Addpolice.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }//GEN-LAST:event_updatepoliceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addpolice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addpolice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Fnamepolice;
    private javax.swing.JButton addpolicesub;
    private javax.swing.JButton clearpolicebtn;
    public javax.swing.JTextField deppolice;
    public javax.swing.JTextField emailpolice;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField lnamepolice;
    public javax.swing.JTextField policeadhar;
    public javax.swing.JTextField policedesig;
    public javax.swing.JTextField policeidjTextField;
    private javax.swing.JButton updatepolice;
    private javax.swing.JButton uploadepolicebtn;
    // End of variables declaration//GEN-END:variables

    String filename= null;
private ImageIcon viewimage=null;
byte [] policeimg=null;


}
