import Crmsconnect.CP;
import java.awt.Image;
import java.security.interfaces.RSAKey;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Student
 */
public class Criminalpage extends javax.swing.JFrame {

    /**
     * Creates new form AddCriminal
     */
     Connection conn=null;
   PreparedStatement insert;
  
    public Criminalpage() throws SQLException {
        initComponents();
         conn=(Connection) CP.dbconnect();
        table_update();
        setTitle("Police Page");
        
        
        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        criminaldelete = new javax.swing.JButton();
        Addcriminalbtn = new javax.swing.JButton();
        Updatecriminal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CrminaljTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cr2 = new javax.swing.JLabel();
        cr4 = new javax.swing.JLabel();
        cr3 = new javax.swing.JLabel();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        imaglabelcr = new javax.swing.JLabel();
        cr1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cr5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 176, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRIMINAL");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        criminaldelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        criminaldelete.setText("DELETE");
        criminaldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criminaldeleteActionPerformed(evt);
            }
        });
        jPanel1.add(criminaldelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 127, 37));

        Addcriminalbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Addcriminalbtn.setText("ADD");
        Addcriminalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddcriminalbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Addcriminalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 140, 127, 37));

        Updatecriminal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Updatecriminal.setText("UPDATE");
        Updatecriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatecriminalActionPerformed(evt);
            }
        });
        jPanel1.add(Updatecriminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 127, 37));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<-");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 510));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrminaljTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Criminal ID", "FNAME", "LNAME", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CrminaljTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrminaljTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CrminaljTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 460, 510));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Preview:");

        jLabel3.setText("Criminal ID:");

        cr2.setText("__________");
        cr2.setPreferredSize(new java.awt.Dimension(46, 16));

        cr4.setText("__________");

        cr3.setText("__________");

        jDesktopPane5.setBackground(new java.awt.Color(204, 204, 204));

        imaglabelcr.setBackground(new java.awt.Color(255, 255, 255));
        imaglabelcr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jDesktopPane5.setLayer(imaglabelcr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imaglabelcr, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imaglabelcr, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        cr1.setText("__________");

        jLabel9.setText("Name:");
        jLabel9.setPreferredSize(new java.awt.Dimension(46, 16));

        jLabel10.setText("Age:");

        jLabel11.setText("FIR ID:");

        jLabel12.setText("Police station:");

        cr5.setText("__________");

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Print ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cr3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(cr5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cr4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cr1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cr2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cr3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cr4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cr5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 260, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public  void table_update() throws SQLException
    {
            int c;
      
             PreparedStatement insert;
            insert = conn.prepareStatement("select * from criminalinfo");
            ResultSet rs= insert.executeQuery();
            ResultSetMetaData res = (ResultSetMetaData) rs.getMetaData();
            c= res.getColumnCount();
            
            
            DefaultTableModel Df=(DefaultTableModel) CrminaljTable.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++){
                v2.add(rs.getString("crminal_id"));
                v2.add(rs.getString("fname"));
                v2.add(rs.getString("lname"));
                v2.add(rs.getString("age"));
                }
                Df.addRow(v2);
            }
    }
    

    
    
    private void AddcriminalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddcriminalbtnActionPerformed
        AddCrminal acpage=new AddCrminal();
        acpage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddcriminalbtnActionPerformed

    private void criminaldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criminaldeleteActionPerformed
         try {
             String deletecriminal=JOptionPane.showInputDialog("Enter criminal Id to delete");
             
             PreparedStatement pst;
             while(deletecriminal.isEmpty()){
                 JOptionPane.showMessageDialog(null, "Check ID","Apocalyptic message", JOptionPane.WARNING_MESSAGE);
                 deletecriminal=JOptionPane.showInputDialog("Enter criminal Id to delete");
             }
             pst=conn.prepareStatement("Select * from criminalinfo Where crminal_id=?");
             pst.setString(1, deletecriminal);
             
             ResultSet res=pst.executeQuery();
             
             if(res.next())
             {
                 pst=conn.prepareStatement("delete from criminalinfo where crminal_id=?");
                 pst.setString(1, deletecriminal);
                 pst.execute();
                 JOptionPane.showMessageDialog(null, "Deleted Successfully");
                 table_update();
                 
             }else{
                 JOptionPane.showMessageDialog(this, "Police ID not Found","Error",JOptionPane.ERROR_MESSAGE);
             }
         } catch (SQLException ex) {
             Logger.getLogger(Criminalpage.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_criminaldeleteActionPerformed

    private void CrminaljTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrminaljTableMouseClicked
       int row=CrminaljTable.getSelectedRow();
       String table_click=(CrminaljTable.getModel().getValueAt(row, 0).toString());
        try {
            String sql="select * from criminalinfo where crminal_id='"+table_click+"'";
            insert=conn.prepareStatement(sql);
            ResultSet rs= insert.executeQuery();
            if(rs.next())
            {
            byte[] imagedata=rs.getBytes("pic");
  
           format=new ImageIcon(imagedata);
           Image img= format.getImage();
           Image imgScaled=img.getScaledInstance(imaglabelcr.getWidth(), imaglabelcr.getHeight(), Image.SCALE_SMOOTH);
           ImageIcon scaledIcon=new ImageIcon(imgScaled);
           imaglabelcr.setIcon(scaledIcon);
            criminalimage=imagedata;
        
         }
             cr1.setText(rs.getString("crminal_id"));
                cr2.setText(rs.getString("fname"));
                cr3.setText(rs.getString("age"));
                cr4.setText(rs.getString("policestation"));
                 cr5.setText(rs.getString("fir_id"));
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
       
       
       
       
       
       
       
       
    }//GEN-LAST:event_CrminaljTableMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Optiontopage opc=new Optiontopage();
       opc.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void UpdatecriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatecriminalActionPerformed
        
        try {
            String Updatecriminal=JOptionPane.showInputDialog("Enter Criminal ID to Update");
            
            
            while(Updatecriminal.isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter please ID","Apocalyptic message", JOptionPane.WARNING_MESSAGE);
                Updatecriminal=JOptionPane.showInputDialog("Enter Crminal Id to delete");
            }
            
            Connection dbConn=(Connection) CP.dbconnect();
            
            PreparedStatement st=(PreparedStatement)dbConn.prepareStatement("Select * from criminalinfo Where crminal_id=?");
            st.setString(1, Updatecriminal);
            
            ResultSet res=st.executeQuery();
            
            if(res.next())
            {
                AddCrminal ap=new AddCrminal(Updatecriminal);
                ap.setVisible(true);
                dispose();
       
            }else{
                JOptionPane.showMessageDialog(this, "Criminal ID not Found","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Criminalpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UpdatecriminalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
         int row=CrminaljTable.getSelectedRow();
       String table_click=(CrminaljTable.getModel().getValueAt(row, 0).toString());
       String table_fir = null;
       
       try {
            String sql="select * from criminalinfo where crminal_id='"+table_click+"'";
            insert=conn.prepareStatement(sql);
            ResultSet rs= insert.executeQuery();
            if(rs.next())
            {
                table_fir=rs.getString("fir_id");
                 System.out.println("Clicked ID is is "+table_click);
                  Printcriminal prp=new Printcriminal(table_click, table_fir);
                  prp.setVisible(true);
                  this.dispose();
         }
             
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criminalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criminalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criminalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criminalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Criminalpage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Criminalpage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addcriminalbtn;
    public javax.swing.JTable CrminaljTable;
    public javax.swing.JButton Updatecriminal;
    private javax.swing.JLabel cr1;
    private javax.swing.JLabel cr2;
    private javax.swing.JLabel cr3;
    private javax.swing.JLabel cr4;
    private javax.swing.JLabel cr5;
    private javax.swing.JButton criminaldelete;
    private javax.swing.JLabel imaglabelcr;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public ImageIcon format=null;
    
    byte[] criminalimage=null;

}
