import Crmsconnect.CP;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Student
 */
public class FIR extends javax.swing.JFrame {

    /**
     * Creates new form Criminal
     */
    
     Connection conn=null;
    public FIR() throws SQLException {
        initComponents();
        conn=(Connection) CP.dbconnect();
        table_update();
        setTitle("FIR Page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Addfir = new javax.swing.JButton();
        Deletefir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        firjTable = new javax.swing.JTable();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 176, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F.I.R");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 78));

        Addfir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Addfir.setText("Add");
        Addfir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddfirActionPerformed(evt);
            }
        });
        jPanel1.add(Addfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 163, 120, 37));

        Deletefir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Deletefir.setText("Delete");
        Deletefir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletefirActionPerformed(evt);
            }
        });
        jPanel1.add(Deletefir, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 273, 120, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIRID", "DATE", "FNAME", "SECTION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(firjTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 500, 470));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 510, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     public  void table_update() throws SQLException
    {
            int c;
      
             PreparedStatement insert;
            insert = conn.prepareStatement("select * from firinfo");
            ResultSet rs= insert.executeQuery();
            ResultSetMetaData res = (ResultSetMetaData) rs.getMetaData();
            c= res.getColumnCount();
            
            
            DefaultTableModel Df=(DefaultTableModel) firjTable.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++){
                v2.add(rs.getString("fir_id"));
                v2.add(rs.getString("dateofcrime"));
                v2.add(rs.getString("fname"));
                v2.add(rs.getString("section"));
                }
                Df.addRow(v2);
            }
    }
    
    
    
    
    
    
    private void AddfirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddfirActionPerformed
        // TODO add your handling code here:
        AddFIR fir1=new AddFIR();
        fir1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddfirActionPerformed

    private void DeletefirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletefirActionPerformed
        
         String deletefir=JOptionPane.showInputDialog("Enter FIR Id to delete");
       
       PreparedStatement pst;
       while(deletefir.isEmpty()){
        JOptionPane.showMessageDialog(null, "Check ID","Apocalyptic message", JOptionPane.WARNING_MESSAGE);
        deletefir=JOptionPane.showInputDialog("Enter criminal Id to delete");
       }
        try {
            pst = conn.prepareStatement("delete from firinfo where fir_id=?");
            pst.setString(1, deletefir);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
            table_update();
        } catch (SQLException ex) {
            Logger.getLogger(FIR.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }//GEN-LAST:event_DeletefirActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Optiontopage firp=new Optiontopage();
        firp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FIR().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FIR.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addfir;
    private javax.swing.JButton Deletefir;
    public javax.swing.JTable firjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
