
import Crmsconnect.CP;
import java.awt.Image;
import static java.lang.String.format;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafiz 01
 */
public class PolicePage extends javax.swing.JFrame {

    /**
     * Creates new form PolicePage
     */
    String tablecon=null;
    Connection conn=null;
    PreparedStatement insert;
    public PolicePage() {
        initComponents();
        conn=(Connection) CP.dbconnect();
        try {
            table_update();
        } catch (SQLException ex) {
            Logger.getLogger(PolicePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTitle("Police Page");
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @throws java.sql.SQLException
     */
    @SuppressWarnings("unchecked")
    public  void table_update() throws SQLException
    {
            int c;
      
            
            insert = conn.prepareStatement("select * from policeinfo");
            ResultSet rs= insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            c= res.getColumnCount();
            
            
            DefaultTableModel Df=(DefaultTableModel) policejTable.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++){
                v2.add(rs.getString("police_id"));
                v2.add(rs.getString("fname"));
                v2.add(rs.getString("designation"));
                v2.add(rs.getString("email"));
                }
                Df.addRow(v2);
            }
            
           
           


}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Updatepolive = new javax.swing.JButton();
        deletpolicebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        policejTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pidlabel = new javax.swing.JLabel();
        pnamelabel = new javax.swing.JLabel();
        pdesiglabel = new javax.swing.JLabel();
        pemaillable = new javax.swing.JLabel();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        imagelabelpl = new javax.swing.JLabel();
        printpolice = new javax.swing.JButton();
        pidlabel1 = new javax.swing.JLabel();
        pnamelabel1 = new javax.swing.JLabel();
        pdesiglabel1 = new javax.swing.JLabel();
        pemaillable1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 176, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 139, 127, 37));

        Updatepolive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Updatepolive.setText("UPDATE");
        Updatepolive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatepoliveActionPerformed(evt);
            }
        });
        jPanel1.add(Updatepolive, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 241, 127, 37));

        deletpolicebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletpolicebtn.setText("DELETE");
        deletpolicebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletpolicebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletpolicebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 345, 127, 37));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POLICE");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, 210, 90));

        policejTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        policejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PoliceID", "FName", "Designation", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        policejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(policejTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 0, 450, 512));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Preview");

        pidlabel.setText("PoliceID:");

        pnamelabel.setText("Name:");
        pnamelabel.setPreferredSize(new java.awt.Dimension(46, 16));

        pdesiglabel.setText("Designation:");

        pemaillable.setText("Email:");

        jDesktopPane5.setBackground(new java.awt.Color(204, 204, 204));

        imagelabelpl.setBackground(new java.awt.Color(255, 255, 255));
        imagelabelpl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jDesktopPane5.setLayer(imagelabelpl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagelabelpl, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagelabelpl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        printpolice.setBackground(new java.awt.Color(204, 255, 255));
        printpolice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printpolice.setText("Print Details");
        printpolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printpoliceActionPerformed(evt);
            }
        });

        pidlabel1.setText("______________");

        pnamelabel1.setText("______________");
        pnamelabel1.setPreferredSize(new java.awt.Dimension(46, 16));

        pdesiglabel1.setText("______________");

        pemaillable1.setText("______________");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pemaillable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pidlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pdesiglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pdesiglabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(printpolice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pemaillable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(72, 72, 72)))))
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pidlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdesiglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdesiglabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pemaillable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemaillable1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printpolice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 0, 340, 512));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Addpolice apo=new Addpolice();
        apo.setVisible(true); 
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletpolicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletpolicebtnActionPerformed
        try {
            
            
            String deletepolice=JOptionPane.showInputDialog("Enter Police Id to delete");
            conn=(Connection) CP.dbconnect();
            
            while(deletepolice.isEmpty()){
                JOptionPane.showMessageDialog(null, "Check ID","Apocalyptic message", JOptionPane.WARNING_MESSAGE);
                deletepolice=JOptionPane.showInputDialog("Enter Police Id to delete");
            }
            
            PreparedStatement pst=conn.prepareStatement("Select * from policeinfo Where police_id=?");
            pst.setString(1, deletepolice);
            
            ResultSet res=pst.executeQuery();
            
            if(res.next())
            {
                pst=conn.prepareStatement("delete from policeinfo where police_id=?");
                pst.setString(1, deletepolice);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
                table_update();
              
            }else{
                JOptionPane.showMessageDialog(this, "Police ID not Found","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PolicePage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    
    }//GEN-LAST:event_deletpolicebtnActionPerformed

    private void UpdatepoliveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatepoliveActionPerformed
       
        
        try {
            String Updatepolice=JOptionPane.showInputDialog("Enter Police Id to Update");
            
            
            while(Updatepolice.isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter please ID","Apocalyptic message", JOptionPane.WARNING_MESSAGE);
                Updatepolice=JOptionPane.showInputDialog("Enter Police Id to delete");
            }
            
            Connection dbConn=(Connection) CP.dbconnect();
            
            PreparedStatement st=(PreparedStatement)dbConn.prepareStatement("Select * from policeinfo Where police_id=?");
            st.setString(1, Updatepolice);
            
            ResultSet res=st.executeQuery();
            
            if(res.next())
            {
                Addpolice ap=new Addpolice(Updatepolice);
                ap.setVisible(true);
                dispose();
       
            }else{
                JOptionPane.showMessageDialog(this, "Police ID not Found","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PolicePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
        
        
    }//GEN-LAST:event_UpdatepoliveActionPerformed

    private void policejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policejTableMouseClicked
        
        int row=policejTable.getSelectedRow();
       String table_click=(policejTable.getModel().getValueAt(row, 0).toString());
      
        try {
            String sql="select * from policeinfo where police_id='"+table_click+"'";
            insert=conn.prepareStatement(sql);
            ResultSet rs= insert.executeQuery();
            if(rs.next())
            {
            byte[] imagedata=rs.getBytes("pic");
  
           format=new ImageIcon(imagedata);
           Image img= format.getImage();
           Image imgScaled=img.getScaledInstance(imagelabelpl.getWidth(), imagelabelpl.getHeight(), Image.SCALE_SMOOTH);
           ImageIcon scaledIcon=new ImageIcon(imgScaled);
           imagelabelpl.setIcon(scaledIcon);
            policeimage=imagedata;
          
         }
            pidlabel1.setText(rs.getString("police_id"));
                pnamelabel1.setText(rs.getString("fname"));
                pdesiglabel1.setText(rs.getString("designation"));
                pemaillable1.setText(rs.getString("email"));
               
                
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_policejTableMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       Optiontopage opp=new Optiontopage();
       opp.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void printpoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printpoliceActionPerformed
       int row=policejTable.getSelectedRow();
       String table_click=(policejTable.getModel().getValueAt(row, 0).toString());
        System.out.println("Clicked ID is is "+table_click);
        Printpolice prp=new Printpolice(table_click);
        prp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_printpoliceActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolicePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Updatepolive;
    private javax.swing.JButton deletpolicebtn;
    private javax.swing.JLabel imagelabelpl;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pdesiglabel;
    private javax.swing.JLabel pdesiglabel1;
    private javax.swing.JLabel pemaillable;
    private javax.swing.JLabel pemaillable1;
    private javax.swing.JLabel pidlabel;
    private javax.swing.JLabel pidlabel1;
    private javax.swing.JLabel pnamelabel;
    private javax.swing.JLabel pnamelabel1;
    public javax.swing.JTable policejTable;
    private javax.swing.JButton printpolice;
    // End of variables declaration//GEN-END:variables

    public ImageIcon format=null;
    
    byte[] policeimage=null;
    
   

    
   
}
