
import Crmsconnect.CP;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafiz 01
 */
public class Printcriminal extends javax.swing.JFrame {

    /**
     * Creates new form Printcriminal
     */
     Connection conn=null;
     PreparedStatement st;
    public Printcriminal() {
        initComponents();
         conn=(Connection) CP.dbconnect();
         setTitle("Print Criminal Details");
       
    }

    Printcriminal(String table_click, String  table_fir) {
      initComponents();
        
        conn=(Connection) CP.dbconnect();
        System.out.println("Print me ID hai: "+table_click);
        
         
        setTitle("Print Criminal Details");
         try {
           st = conn.prepareStatement("SELECT criminalinfo.fname, criminalinfo.lname, criminalinfo.age,criminalinfo.crminal_id,criminalinfo.fir_id,firinfo.section FROM criminalinfo inner join firinfo on criminalinfo.fir_id=firinfo.fir_id where criminalinfo.fir_id=?");
           st.setString(1, table_fir);
           
            ResultSet rs= st.executeQuery();
            if(rs.next()){
            cp1.setText(rs.getString("fname"));
            cp2.setText(rs.getString("lname"));
            cp3.setText(rs.getString("age"));
            cp4.setText(rs.getString("crminal_id"));
            cp5.setText(rs.getString("fir_id"));
            cp6.setText(rs.getString("section"));
            
            
             JOptionPane.showMessageDialog(null, "You can Print");
            }
        
    }    catch (SQLException ex) {
             Logger.getLogger(Printpolice.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cp1 = new javax.swing.JLabel();
        cp3 = new javax.swing.JLabel();
        cp2 = new javax.swing.JLabel();
        cp4 = new javax.swing.JLabel();
        cp5 = new javax.swing.JLabel();
        cp6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRIMINAL DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 380, 44));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 50, 380, -1));

        jLabel2.setText("First name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 80, 24));

        jLabel3.setText("Last name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, 80, 24));

        jLabel4.setText("Age");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 55, 24));

        jLabel5.setText("Crminal ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, -1, 24));

        jLabel6.setText("FIR ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 244, 55, 24));

        jLabel7.setText("Section:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 286, 55, 24));

        cp1.setText("____________");
        jPanel1.add(cp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 76, 190, 24));

        cp3.setText("____________");
        jPanel1.add(cp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 160, 190, 24));

        cp2.setText("____________");
        jPanel1.add(cp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 118, 190, 24));

        cp4.setText("____________");
        jPanel1.add(cp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 202, 190, 24));

        cp5.setText("____________");
        jPanel1.add(cp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 244, 190, 24));

        cp6.setText("____________");
        jPanel1.add(cp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 286, 190, 24));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 328, 108, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<-");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PrinterJob job=PrinterJob.getPrinterJob();
       job.setJobName("Print Data");
       
       job.setPrintable(new Printable() {
           @Override
           public int print(Graphics pg, PageFormat pf, int pageNum) throws PrinterException {
               pf.setOrientation(PageFormat.LANDSCAPE);
               if(pageNum>0){
               return Printable.NO_SUCH_PAGE;
               }
               
               Graphics2D g2=(Graphics2D)pg;
               g2.translate(pf.getImageableX(), pf.getImageableY());
               g2.scale(0.47,0.47);
               
               jPanel1.paint(g2);
               
               return Printable.PAGE_EXISTS;
               
           }
       });
       
       boolean ok=job.printDialog();
       if(ok){
           try {
               job.print();
           } catch (Exception e) {
               System.out.println(e);
           }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         try {
             Criminalpage crp=new Criminalpage();
             crp.setVisible(true);
             this.dispose();
         } catch (SQLException ex) {
             Logger.getLogger(Printcriminal.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Printcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Printcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Printcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Printcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Printcriminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cp1;
    private javax.swing.JLabel cp2;
    private javax.swing.JLabel cp3;
    private javax.swing.JLabel cp4;
    private javax.swing.JLabel cp5;
    private javax.swing.JLabel cp6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
