
import Crmsconnect.CP;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Student
 */
public class Rehab extends javax.swing.JFrame {

    /**
     * Creates new form Rehab
     */
    
    Connection conn=null;
    public Rehab() {
        try {
            initComponents();
            
            conn=(Connection) CP.dbconnect();
            table_update();
            setTitle("Rehab Page");
        } catch (SQLException ex) {
            Logger.getLogger(Rehab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rehabaddbtn = new javax.swing.JButton();
        deletrehab = new javax.swing.JButton();
        sugbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rehabjTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 176, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REHABILITATION");
        jLabel1.setMaximumSize(new java.awt.Dimension(119, 49));
        jLabel1.setMinimumSize(new java.awt.Dimension(119, 49));
        jLabel1.setPreferredSize(new java.awt.Dimension(119, 49));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 210, 40));

        rehabaddbtn.setText("ADD");
        rehabaddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rehabaddbtnActionPerformed(evt);
            }
        });
        jPanel1.add(rehabaddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 149, 119, 37));

        deletrehab.setText("DELETE");
        deletrehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletrehabActionPerformed(evt);
            }
        });
        jPanel1.add(deletrehab, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 314, 119, 37));

        sugbtn.setText("SUGGESTIONS");
        sugbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugbtnActionPerformed(evt);
            }
        });
        jPanel1.add(sugbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 233, 119, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rehabjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CRIMINAL ID", "DURATION", "Mentor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rehabjTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public  void table_update() throws SQLException
    {
            int c;
      
             PreparedStatement insert;
            insert = conn.prepareStatement("select * from rehabinfo");
            ResultSet rs= insert.executeQuery();
            ResultSetMetaData res = (ResultSetMetaData) rs.getMetaData();
            c= res.getColumnCount();
            
            
            DefaultTableModel Df=(DefaultTableModel) rehabjTable.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1; a<=c; a++){
                v2.add(rs.getString("criminal_id"));
                v2.add(rs.getString("duration"));
                v2.add(rs.getString("mentor"));
                }
                Df.addRow(v2);
            }
    }
    
    
    
    
    
    
    
    
    
    private void rehabaddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehabaddbtnActionPerformed
        // TODO add your handling code here:
        ADDrehab rhb2=new ADDrehab();
        rhb2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_rehabaddbtnActionPerformed

    private void sugbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugbtnActionPerformed
        suggestcr sg=new suggestcr();
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sugbtnActionPerformed

    private void deletrehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletrehabActionPerformed
       String deleterehab=JOptionPane.showInputDialog("Enter criminal Id to delete");
       
       PreparedStatement pst;
       while(deleterehab.isEmpty()){
        JOptionPane.showMessageDialog(null, "Check ID","Apocalyptic message", JOptionPane.WARNING_MESSAGE);
        deleterehab=JOptionPane.showInputDialog("Enter criminal Id to delete");
       }
        try {
            pst = conn.prepareStatement("delete from rehabinfo where criminal_id=?");
            pst.setString(1, deleterehab);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
            table_update();
        } catch (SQLException ex) {
            Logger.getLogger(Rehab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletrehabActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Optiontopage opr=new Optiontopage();
        opr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rehab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rehab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rehab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rehab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rehab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletrehab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rehabaddbtn;
    public javax.swing.JTable rehabjTable;
    private javax.swing.JButton sugbtn;
    // End of variables declaration//GEN-END:variables
}
