
import Crmsconnect.CP;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Walter
 */
public class suggestcr extends javax.swing.JFrame {

    /**
     * Creates new form suggestcr
     */
     Connection conn=null;
    public suggestcr() {
        initComponents();
        conn=(Connection) CP.dbconnect();
        
        //code here 
        PreparedStatement st;
        setTitle("Suggestion Page");
         try {
           st = conn.prepareStatement("select c.fname,f.typeofcrime,f.section,f.fir_id from criminalinfo as c inner join firinfo as f on c.fir_id=f.fir_id where section=?");
            st.setString(1,"307");
            ResultSet rs= st.executeQuery();
            if(rs.next()){
            ncr.setText(rs.getString("fname"));
            scr.setText(rs.getString("section"));
            tycr.setText(rs.getString("typeofcrime"));
            fcr.setText(rs.getString("fir_id"));
            
             JOptionPane.showMessageDialog(null, "Showing suggestion for rehabilitation");
            }
        
    }    catch (SQLException ex) {
             Logger.getLogger(Printpolice.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        frid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ncr = new javax.swing.JLabel();
        scr = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tycr = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fcr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("Type of Crime");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frid.setBackground(new java.awt.Color(255, 255, 255));
        frid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suggestion for Criminal rehab");
        frid.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -8, 360, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Name:");
        frid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 29));

        ncr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frid.add(ncr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, 29));

        scr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frid.add(scr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 160, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Section:");
        frid.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, 20));

        tycr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frid.add(tycr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Type of Crime:");
        frid.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 30));

        fcr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frid.add(fcr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("F.I.R ID:");
        frid.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frid, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suggestcr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suggestcr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suggestcr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suggestcr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suggestcr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fcr;
    private javax.swing.JPanel frid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel ncr;
    private javax.swing.JLabel scr;
    private javax.swing.JLabel tycr;
    // End of variables declaration//GEN-END:variables
}
